### ISSUE TITLE
複数の商品をレンダリング

### ISSUE THREAD

**Issue by watasan1012** [vuejs-jp/handson-vue3#143]
[https://handson.vuejs-jp.org/v-for.html#%E8%A4%87%E6%95%B0%E3%81%AE%E5%95%86%E5%93%81%E3%82%92%E3%83%AC%E3%83%B3%E3%82%BF%E3%82%99%E3%83%AA%E3%83%B3%E3%82%AF%E3%82%99](https://handson.vuejs-jp.org/v-for.html#%E8%A4%87%E6%95%B0%E3%81%AE%E5%95%86%E5%93%81%E3%82%92%E3%83%AC%E3%83%B3%E3%82%BF%E3%82%99%E3%83%AA%E3%83%B3%E3%82%AF%E3%82%99)

```
同時に指定している key 属性は、 v-for で取り出した各要素を一意（ユニーク）にするために推奨されているものです。一意にすることで、 Vue.js が要素の再利用や並び替えをする手助けになります。 詳細は [Vue.jsドキュメントガイド 状態の維持 (opens new window)](https://v3.ja.vuejs.org/guide/list.html#%E7%8A%B6%E6%85%8B%E3%81%AE%E7%B6%AD%E6%8C%81)を参照してください。

変更前
```
とあるのですが、これは、変更後のコードの後に表示した方がいいと思います。

**Comment by k-miyake** [comment]
フィードバックありがとうございます。 #129 の対応の中に取り込むべきか検討していきます。

**Comment by k-miyake** [comment]
@watasan1012 フィードバックの通り、コードの後に解説を移動しました。ご確認ください。
https://handson.vuejs-jp.org/v-for.html#v-for-%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9:~:text=B%0A%E3%83%BB%E3%82%BF%E3%82%B9%E3%82%AFC-,%23,-%E8%A4%87%E6%95%B0%E3%81%AE%E5%95%86%E5%93%81
