### ISSUE TITLE
v-if で表示・非表示を切り替える

### ISSUE THREAD

**Issue by watasan1012** [vuejs-jp/handson-vue3#144]
[v-if で表示・非表示を切り替える](https://handson.vuejs-jp.org/v-if.html#v-if-%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9)

プロパティの追加をしているのですが。

v-for で商品を複数表示するで、ref　対応しているので、合わせた方がいいかもしれません。

**Comment by watasan1012** [comment]
<script setup>
import { ref } from 'vue'

const items = ref([
  {
    id: 1,
    name: 'アボカドディップバケット',
    description:
      '刻んだ野菜をアボカドと混ぜてディップに。こんがり焼いたバゲットとお召し上がりください。',
    price: 480,
    image: '/images/item1.jpg',
    soldOut: false
  },
  {
    id: 2,
    name: 'あの日夢見たホットケーキ',
    description:
      '子供のころに食べたかった、あのホットケーキを再現しました。素朴でどこか懐かしい味をどうぞ。',
    price: 1180,
    image: '/images/item2.jpg',
    soldOut: false
  },
  {
    id: 3,
    name: 'HOP WTR',
    description:
      'ロサンゼルス生まれのスパークリングウォーター。ノンカロリー、ノンアルコールの新感覚飲料です。',
    price: 320,
    image: '/images/item3.jpg',
    soldOut: true
  },
  {
    id: 4,
    name: 'チーズフレンチフライ',
    description:
      'イタリア産チーズをたっぷりかけたアツアツのフレンチフライ。みんな大好きな一品です。',
    price: 670,
    image: '/images/item4.jpg',
    soldOut: false
  }
])
</script>

**Comment by k-miyake** [comment]
フィードバックありがとうございます。#125 にて反映されているかを確認します。

**Comment by k-miyake** [comment]
@watasan1012 `ref()` を使った書き方に変わっていますのでご確認をお願いします。
https://handson.vuejs-jp.org/v-if.html#%E3%83%95%E3%82%9A%E3%83%AD%E3%83%8F%E3%82%9A%E3%83%86%E3%82%A3%E3%81%AE%E8%BF%BD%E5%8A%A0
