### ISSUE TITLE
コンポーネントを解説する章を新規追加する

### ISSUE THREAD

**Issue by k-miyake** [vuejs-jp/handson-vue3#146]
カードをコンポーネント化しApp.vueで使う
- 一部をモジュールとして切り出し、ページと部品で分けられる
- props と emit でのデータ・イベントのやり取りを含める

**Comment by nalpan** [comment]
@nalpan ハンズオンでも話すので内容を見ておく

**Comment by k-miyake** [comment]
#155 で対応済み
