### ISSUE TITLE
vue.js のプロジェクト作成

### ISSUE THREAD

**Issue by harop** [vuejs-jp/handson-vue3#156]
https://github.com/vuejs-jp/handson-vue3/blob/main/docs/create.md

3.npm run dev の実行が完了したら、ブラウザで http://localhost:3000/ にアクセスします。

 http://localhost:3000/　の数字ですが。環境によって変わる可能性があるみたいです。

自分の場合は以下の表示でした。

```
 % npm run dev

> vue3-lab@0.0.0 dev
> vite


  VITE v3.0.4  ready in 221 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
```

**Comment by nalpan** [comment]
Vite v3による変更みたいです 👀
https://ja.vitejs.dev/guide/migration.html#%E9%96%8B%E7%99%BA%E3%82%B5%E3%83%BC%E3%83%90%E3%81%A7%E3%81%AE%E5%A4%89%E6%9B%B4

ガイドが変更になりそうです
