### ISSUE TITLE
data を定義し、商品をレンダリングする #

### ISSUE THREAD

**Issue by harop** [vuejs-jp/handson-vue3#157]
リンク [https://handson.vuejs-jp.org/rendering.html#mustache-%E6%A7%8B%E6%96%87](https://handson.vuejs-jp.org/rendering.html#mustache-%E6%A7%8B%E6%96%87)

タイトル 商品をレンダリング

変更前（template）下の変更前のコード

```
<template>
  <img
    alt="Vue logo"
    src="./assets/logo.png">
  <HelloWorld msg="Welcome to Your Vue.js App" />
</template>
```

自分の表示結果

```
<template>
  <header>
    <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />

    <div class="wrapper">
      <HelloWorld msg="You did it!" />
    </div>
  </header>

  <main>
    <TheWelcome />
  </main>
</template>
```

記載が違うようです。

**Comment by k-miyake** [comment]
@harop ご指摘ありがとうございます。最新の `create-vue` では生成されるコードが変更されるようです。最新に合わせて対応していきたいと思います。
