### ISSUE TITLE
商品をレンダリング scriptタグの変更前の記述が違う？

### ISSUE THREAD

**Issue by harop** [vuejs-jp/handson-vue3#158]
リンク [https://handson.vuejs-jp.org/rendering.html#mustache-%E6%A7%8B%E6%96%87](https://handson.vuejs-jp.org/rendering.html#mustache-%E6%A7%8B%E6%96%87)

タイトル 商品をレンダリング

変更前（script）下の変更前のコード

```
<script>
import HelloWorld from './components/HelloWorld.vue'

export default {
  name: 'App',
  components: {
    HelloWorld
  }
}
</script>
```

自分の表示結果

```
<script setup>
import HelloWorld from './components/HelloWorld.vue'
import TheWelcome from './components/TheWelcome.vue'
</script>
```

記載が違うようです。

**Comment by k-miyake** [comment]
@harop こちらも最新の create-vue では生成されるコードが変更されるようです。最新に合わせて対応していきたいと思います。

**Comment by k-miyake** [comment]
#161 で解消されましたのでクローズさせていただきます
