### ISSUE TITLE
#data を定義し、商品をレンダリングする　商品をレンダリング

### ISSUE THREAD

**Issue by harop** [vuejs-jp/handson-vue3#159]
リンク　https://handson.vuejs-jp.org/rendering.html#mustache-%E6%A7%8B%E6%96%87

見た目を設定するために style タグの中身を以下のように置き換えます。

のあとで、npm run devでサーバーを起動すると見た目がおかしい

main.js に

import './assets/main.css'

の記載があって、みためがおかしくなっている可能性があります。　一行コメントアウトするとその後のcssレイアウトがサンプルと同じになります。

**Comment by k-miyake** [comment]
@harop こちらも最新の create-vue では生成されるコードが変更されるようです。最新に合わせて対応していきたいと思います。

**Comment by k-miyake** [comment]
#161 で解消しましたのでクローズさせていただきます
