### ISSUE TITLE
タイトル名について v-on:click

### ISSUE THREAD

**Issue by harop** [vuejs-jp/handson-vue3#162]
<img width="377" alt="スクリーンショット 2022-08-11 15 10 31" src="https://user-images.githubusercontent.com/16369076/184073951-1f84153f-8321-408d-a44c-8f20ca1a8171.png">

**Comment by harop** [comment]
対象URL [https://handson.vuejs-jp.org/#vue-js-%E3%82%92%E3%81%AF%E3%81%97%E3%82%99%E3%82%81%E3%82%88%E3%81%86](https://handson.vuejs-jp.org/#vue-js-%E3%82%92%E3%81%AF%E3%81%97%E3%82%99%E3%82%81%E3%82%88%E3%81%86)

**Comment by k-miyake** [comment]
@harop  `@click` は `v-on:click` の省略形で、このガイドでは最終的に `@click` で書くため問題ないと思っています。

**Comment by k-miyake** [comment]
講師の方のチェックも通ったのでこちらはクローズさせていただきます
