### ISSUE TITLE
プロジェクトの作成 -プロジェクトの起動

### ISSUE THREAD

**Issue by watasan1012** [vuejs-jp/handson-vue3#167]
プロジェクトの作成ページ　
https://handson.vuejs-jp.org/create.html#%E3%83%95%E3%82%9A%E3%83%AD%E3%82%B7%E3%82%99%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E8%B5%B7%E5%8B%95

3. npm run dev の実行が完了したら、ブラウザで http://localhost:5137/ にアクセスします。

URLの数字が違う。5173

3 . npm run dev の実行が完了したら、ブラウザで http://localhost:5173/ にアクセスします。

参考資料

https://ja.vitejs.dev/config/server-options.html#server-port

**Comment by k-miyake** [comment]
#166 が修正しましたのでクローズします
