### ISSUE TITLE
Vue.js を使わない場合 のhtml タグ

### ISSUE THREAD

**Issue by watasan1012** [vuejs-jp/handson-vue3#168]
Vue.js を使わない場合 のhtml

html 5では、

`<meta charset="UTF-8" />`

/ の閉じタグは不要です

`<link rel="icon" href="/favicon.ico" />`

/ の閉じタグは不要です

`<meta name="viewport" content="width=device-width, initial-scale=1.0" />`

/ の閉じタグは不要です

`<img src="./images/logo.svg" alt="" />`

/ の閉じタグは不要です

対象URL
https://handson.vuejs-jp.org/overview.html#%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B%E3%82%82%E3%81%AE

参考URL
https://validator.w3.org/nu/

**Comment by nalpan** [comment]
@watasan1012 
`create-vue` で生成された `index.html` では `/>` となっているため現状ではこちらを優先させてください 🙇
