### ISSUE TITLE
DOM 要素に v-if を追加 の下のコード

### ISSUE THREAD

**Issue by watasan1012** [vuejs-jp/handson-vue3#172]
DOM 要素に v-if を追加　の下のコードですが

変更後のコード
```
      <div
        v-if="!item.soldOut"
        class="item">
        <div class="thumbnail">
          <img
            :src="item.image"
            alt="">
        </div>
        <div class="description">
          <h2>{{ item.name }}</h2>
          <p>{{ item.description }}</p>
          <span>¥<span class="price">{{ item.price }}</span></span>
        </div>
      </div>
```

ハイライト部分が大きいと思います。

```
        v-if="!item.soldOut"
```

の部分が変更点なので、この部分のみハイライトして欲しいと思います。

参考URL 
https://handson.vuejs-jp.org/v-if.html#%E3%83%95%E3%82%9A%E3%83%AD%E3%83%8F%E3%82%9A%E3%83%86%E3%82%A3%E3%81%AE%E8%BF%BD%E5%8A%A0

**Comment by happylifetaka** [comment]
@watasan1012 変更前の時点で、 `<div class="item">` のタグの範囲をハイライトしているので問題ないようにも見えました。
v-forの章でも同様ですね。追加差分だけハイライトする方がよいのか、着目する範囲をハイライトするのか、全体のルールを確認した方がよさそうです。

<img width="773" alt="image" src="https://user-images.githubusercontent.com/31531180/233791501-444ab79e-f43e-4c25-a9a6-cd86e4e870f2.png">
