### ISSUE TITLE
キー修飾子を使ったキーボードイベントの使い方- キー修飾子の書き方

### ISSUE THREAD

**Issue by watasan1012** [vuejs-jp/handson-vue3#173]
キー修飾子を使ったキーボードイベントの使い方

App.vue template
```
<input v-on:keyup.enter="alert" />
```

App.vue script
```
<script setup>
// ...省略

function alert() {
  alert('keyup')
}
</script>
```

テキストボックスにテキストを入れてエンターキーを入れてもalertが表示されない。
コンソールログにはエラーが表示される。

添付画像参照ください

一例で、console.logにするとコンソールに表示されます
```
<script setup>
function alert() {
  console.log('test');
  // alert('keyup')
}
</script>
```

教材URL

https://handson.vuejs-jp.org/event.html#%E3%82%AD%E3%83%BC%E4%BF%AE%E9%A3%BE%E5%AD%90%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9F%E3%82%AD%E3%83%BC%E3%83%9B%E3%82%99%E3%83%BC%E3%83%88%E3%82%99%E3%82%A4%E3%83%98%E3%82%99%E3%83%B3%E3%83%88%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9

参考URL

https://v3.ja.vuejs.org/guide/migration/keycode-modifiers.html#_2-x-%E3%81%A6%E3%82%99%E3%81%AE%E6%A7%8B%E6%96%87

**Comment by watasan1012** [comment]
<img width="1404" alt="スクリーンショット 2022-10-07 17 59 41" src="https://user-images.githubusercontent.com/103015617/194515664-73fa0f2b-f1f1-41ce-bef5-a3f4bd123995.png">

**Comment by k-miyake** [comment]
ご指摘ありがとうございます。再現しました。PRを作って修正対応します。
