### ISSUE TITLE
言語ブロックの順番を入れ替える

### ISSUE THREAD

**Issue by totocalcio** [vuejs-jp/handson-vue3#178]
`<script setup>`ブロックの登場以降、`<script setup>` → `<template>` → `<style>` の順番で記述されるようになったため統一する。

**Comment by watasan1012** [comment]
ハンズオン概要 → Vue.js を使った場合のプログラム → App.vue のコードの変更を忘れずにしたい。
[Vue.js を使った場合のプログラムのApp.vue](https://handson.vuejs-jp.org/overview.html
