### ISSUE TITLE
Volar の GitHub リポジトリ

### ISSUE THREAD

**Issue by watasan1012** [vuejs-jp/handson-vue3#206]
Volar (Vue Language Features) 拡張機能のインストール
Volar は Vue.js の開発をサポートする VS Code の拡張機能です。.vue ファイルのシンタックスハイライトやインテリセンスによる補完ができるようになります。詳細は、[Volar の GitHub リポジトリ](https://github.com/johnsoncodehk/volar/) を参照してください。

Volar の GitHub リポジトリ　→ language-tools の GitHub リポジトリ　

に名称変更？したようなので変更？

**Comment by totocalcio** [comment]
プラグイン名も必要であれば合わせたほうがいいかもしれない。

Volar (Vue Language Features) 拡張機能のインストール
→Vue Language Features (Volar)拡張機能のインストール

https://marketplace.visualstudio.com/items?itemName=Vue.volar
