### ISSUE TITLE
Vue.js または、Vueが併用されている

### ISSUE THREAD

**Issue by watasan1012** [vuejs-jp/handson-vue3#207]
https://ja.vuejs.org/guide/introduction.html#what-is-vue を参照すると本文は、Vue で.jsは記載されていないようです。ですが。headerは、Vue.jsで.js表記があります。
ルールを統一した方がいいかと思います。

**Comment by k-miyake** [comment]
ご指摘ありがとうございます。表記上どちらかに寄せるべきかどうかも含めて検討します。ただし、実際の修正は影響範囲が非常に大きくなるため、本件は中長期的な課題として扱いたいと思います。
