### ISSUE TITLE
v-forの変更点がわかりにくい

### ISSUE THREAD

**Issue by watasan1012** [vuejs-jp/handson-vue3#208]
参考URL
https://handson.vuejs-jp.org/v-for.html

複数の商品をレンダリング

変更後

```
    <template
      v-for="item in items"
      :key="item.id">
```

```
 </template>
```

変更する部分のハイライトが全体にかかってるのですが。変更する部分だけハイライトするといいと思いました。

**Comment by k-miyake** [comment]
内容を確認しましたが、変更する部分に正しくハイライトされているようでした。再度ご確認いただけますでしょうか？
