### ISSUE TITLE
文章の校正

### ISSUE THREAD

**Issue by watap7** [vuejs-jp/handson-vue3#64]
overview.md > ## 作成するもの >  このハンズオンでは、簡単な商品の一覧を表示し、購入する商品を選択できるプログラムを作成します。プログラムを作成する過程で、 Vue.js の基本を学ぶことができます。実際に動く物は こちら から見れます。 → 見れます。 → 見られます。 　「ら」抜き

**Comment by 448jp** [comment]
@watap7 
> 「ら」抜き

ウォークスルーで修正しました。

> 綺麗 → 奇麗

「スマート」に言い換えました。
