### ISSUE TITLE
v-forの章でシンタックスハイライトが効いてないので調べる。

### ISSUE THREAD

**Issue by happylifetaka** [vuejs-jp/handson-vue3#87]
![image](https://user-images.githubusercontent.com/31531180/134157078-c4b68195-2964-422f-9bfd-6c1b7abfc5f9.png)

**Comment by k-miyake** [comment]
@YuukiIshibashi こちらの対応よろしくお願いします。

**Comment by k-miyake** [comment]
https://github.com/vuejs-jp/handson-vue3/commit/b530a36f3e8d6872300d206cfe216ca75c310bf5 で対応されているのでクローズします。
