### ISSUE TITLE
ガイドの導入の完成品へのリンクを追加する

### ISSUE THREAD

**Issue by happylifetaka** [vuejs-jp/handson-vue3#92]
overview.mdで、一時的に、ガイドの導入の完成品へのリンクを消しているので、ガイドの導入の完成品へのリンクを追加する

- [x] 完成品のホスト
- [ ] 完成品リンクの復活

**Comment by k-miyake** [comment]
@happylifetaka これはもう対応不要ですかね？

**Comment by happylifetaka** [comment]
@k-miyake 現状完成版をすぐに見れるページはないので、ベータの時点では画面共有とかでカバーしようかなと考えています。

**Comment by k-miyake** [comment]
GitHub Pages の別ディレクトリにホスティングできないか調査する

**Comment by k-miyake** [comment]
Cloudflare にホスティングする検証を実施した。
- https://5e8e47aa.handson-vue3.pages.dev/

**Comment by k-miyake** [comment]
https://handson-example.vuejs-jp.org/ にてホスト済み
