### ISSUE TITLE
VuePress で出力したサイトに Favicon を付けたい

### ISSUE THREAD

**Issue by k-miyake** [vuejs-jp/handson-vue3#98]
以下の対応で実現できそう
- VuePress 出力先の `public` に favicon 用画像ファイルを置く
- `config.js` に head の設定を入れる (https://vuepress.vuejs.org/config/#head)

以下は要検討
- favicon 用画像はどれを使うか？（Vue.js-jp サイトと同じで良い？）

**Comment by 448jp** [comment]
> favicon 用画像はどれを使うか？（Vue.js-jp サイトと同じで良い？）

Vue.js-jpと同じでよいと思います！　Vue.js-jpのオフィシャルコンテンツ感もでますし。
